apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-resultdataservice
  labels:
    ci: phaedra2-resultdataservice-build
spec:
  containers:
   - name: builder
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true
     #volumeMounts:
      #- mountPath: /home/jenkins/maven-repository
        #name: ci-phaedra2-maven-repository
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
  #name: "ci-phaedra2-maven-repository"
#spec:
  #accessModes:
    #- ReadWriteMany
  #resources:
    #requests:
      #storage: 20Gi

