server:
  servlet:
    context-path: /phaedra/resultdata-service
  port: 6010

spring:
  cloud:
    kubernetes:
      enabled: false
  application:
    name: phaedra-resultdata-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost
  graphql:
    graphiql:
      enabled: true
  jackson:
    serialization:
      indent_output: true


