FROM 772435625456.dkr.ecr.eu-west-1.amazonaws.com/phaedra2/liquibase:latest
ADD src/main/resources/db/changelog /liquibase/changelog
CMD ["sh", "-c", "docker-entrypoint.sh --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} --defaultSchemaName=${DB_SCHEMA} --classpath=/liquibase/changelog --changeLogFile=db.changelog-master.yaml update"]
